### ISSUE TITLE
Does the current module support the following features?

### ISSUE THREAD

**Issue by Udayaprasad** [mgroupntua/MSolve.FEM#13]
@dimtsap  Does the current module support the following features?

Spring-Tension Only/Compression Only
Rigid Elements for connection
Temperature Load Application

**Comment by dimtsap** [comment]
The current version supports spring elements but not the special tension/compression only cases you mentioned. Also thermal problems are supported so you can apply temperatures as a boundary condition. The coupled thermo-mechanical solver is currently under development. In the next release, which is expected in the next few months, the penalty method is implemented which can be used for the rigid element connection you require. In any case, since this is a open-source project we are open to your contribution and we provide you the contributing guidelines that guide you through the process.
